# To activate, change the Appveyor settings to use `.appveyor.yml`.
environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py33
    - TOXENV: py34
    - TOXENV: py35
    - TOXENV: py36

install:
  - pip install tox

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - tox

matrix:
  fast_finish: true
