# To activate, change the Appveyor settings to use `.appveyor.yml`.
environment:
  matrix:
    - TOXENV: pypy
    - TOXENV: pypy3

install:
  - pip install tox

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - tox
