environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py33
    - TOXENV: py34
    - TOXENV: py35
    - TOXENV: py36
install:
  - pip install tox
build: false
test_script:
  - tox
matrix:
  fast_finish: true
branches:
  only:
    - master
