sudo: false
language: python
python:
 - "3.5"

env:
 - SETUPTOOLS_VERSION=13.0.2
 - SETUPTOOLS_VERSION=14.3
 - SETUPTOOLS_VERSION=15.2
 - SETUPTOOLS_VERSION=16.0
 - SETUPTOOLS_VERSION=17.1.1
 - SETUPTOOLS_VERSION=18.8
 - SETUPTOOLS_VERSION=19.7
 - SETUPTOOLS_VERSION=20.10.1
 - SETUPTOOLS_VERSION=21.2.2
 - SETUPTOOLS_VERSION=22.0.5
 - SETUPTOOLS_VERSION=23.2.1
 - SETUPTOOLS_VERSION=24.0.3

before_install:
 # Save the setuptools version
 - ORIG_SETUPTOOLS_VERSION=`python -c "import setuptools; print('%s' % setuptools.__version__)"`
 - echo setuptools $ORIG_SETUPTOOLS_VERSION
install:
 # A recent setuptools is needed to parse setup.py to create the wheel
 - pip install --upgrade setuptools==$SETUPTOOLS_VERSION wheel
 - python setup.py bdist_wheel
 # Reset to original setuptools to confirm the wheel can be installed on
 # Travis without any extra installation steps
 - pip install --upgrade setuptools==$ORIG_SETUPTOOLS_VERSION
 - pip install ./dist/tox_travis-*.whl
script:
 - tox --installpkg ./dist/tox_travis-*.whl

matrix:
  fast_finish: true
