sudo: false
language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
 - "pypy3"
 - "pypy3.3-5.2-alpha1"
 - "nightly"

before_install:
 # Show the current setuptools version
 - ORIG_SETUPTOOLS_VERSION=`python -c "import setuptools; print('%s' % setuptools.__version__)"`
 - echo setuptools $ORIG_SETUPTOOLS_VERSION
install:
 - pip install wheel
 - python setup.py install bdist_wheel
 - pip install ./dist/tox_travis-*.whl
script:
 - tox
 - tox --installpkg ./dist/tox_travis-*.whl
