sudo: false
language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "pypy"
 - "pypy3"
 - "pypy3.3-5.2-alpha1"
 - "pypy3.3-5.5-alpha"

install:
  - pip install wheel codecov coverage
  - python setup.py bdist_wheel
  - pip install ./dist/tox_travis-*.whl
script: tox --installpkg ./dist/tox_travis-*.whl
after_success: coverage combine && codecov
